### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GrimPixel** [Tech-FZ/EmuGUI#63]
```
Traceback (most recent call last):
  File "emugui.py", line 999, in prepareDatabase
AttributeError: 'NoneType' object has no attribute 'split'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "emugui.py", line 2555, in <module>
  File "emugui.py", line 98, in __init__
  File "emugui.py", line 1029, in prepareDatabase
AttributeError: 'NoneType' object has no attribute 'split'
[393046] Failed to execute script 'emugui' due to unhandled exception!
```

**Comment by Tech-FZ** [comment]
Can you please tell me which version of Windows you used, which version of EmuGUI you used and which version of QEMU you used. Also, it would be helpful if I knew how you got this error.

**Comment by GrimPixel** [comment]
It was the latest release on an Arch Linux and the operating system is gone now. I am using Manjaro and the error doesn't appear again.
